# ~/.config/foot/foot.ini

[main]
font=MesloLGSNerdFont:size=12
pad=16x10
# dpi-aware=no

[colors-dark]
alpha=0.95
foreground=d0d0d0
background=000010

# Normal colors
# black, red, green, yellow, blue, magenta, cyan, white
regular0=151515
regular1=ac4142
regular2=90a959
regular3=f4bf75
regular4=6a9fb5
regular5=aa759f
regular6=75b5aa
regular7=d0d0d0

# Bright colors
# bright black, red, green, yellow, blue, magenta, cyan, white
bright0=505050
bright1=ac4142
bright2=90a959
bright3=f4bf75
bright4=6a9fb5
bright5=aa759f
bright6=75b5aa
bright7=f5f5f5

[key-bindings]
# increase-font-size=Control+plus Control+equal Control+KP_Add
# decrease-font-size=Control+minus Control+KP_Subtract
# reset-font-size=Control+0 Control+KP_0
